import * as Constants from './constants';

export const initialState = {
    player: null,
    room: null,
    roomPlayers: [],
    deck: [],
    cards: [
        {
            id: "VIRUS1",
            type: Constants.CARD_TYPE_VIRUS,
            name: "Virus",
            description: "Infections Killing Virus initial stage",
            action: Constants.ACTION_INCREMENT_VIRUS_TOKEN,
            increment: 1,
        },
        {
            id: "R1",
            type: Constants.CARD_TYPE_RESOURCE,
            name: "Social Distancing",
            description: "Prevent a virus card to increment tokens",
            action: Constants.ACTION_CONTAIN_VIRUS,
            impactedVirusCards: 1,
        },
        {
            id: "R2",
            type: Constants.CARD_TYPE_RESOURCE,
            name: "Quarantine/Lockdown",
            description: "Prevent 3 virus cards to increment tokens",
            action: Constants.ACTION_CONTAIN_VIRUS,
            impactedVirusCards: 3,
        },
        {
            id: "R3",
            type: Constants.CARD_TYPE_RESOURCE,
            name: "Masks and Ventilators",
            description: "destroy one virus token",
            action: Constants.ACTION_DESTROY_VIRUS_TOKEN,
            impactedVirusCards: 1,
        },
        {
            id: "R4",
            type: Constants.CARD_TYPE_RESOURCE,
            name: "Medics",
            description: "destroy three virus token",
            action: Constants.ACTION_DESTROY_VIRUS_TOKEN,
            impactedVirusCards: 3,
        },
        {
            id: "A1",
            type: Constants.CARD_TYPE_ADVANTAGE,
            name: "Educated Population",
            description: "Each round prevents a virus card to increment token",
            action: Constants.ACTION_CONTAIN_VIRUS,
            impactedVirusCards: 1,
        },
        {
            id: "A2",
            type: Constants.CARD_TYPE_ADVANTAGE,
            name: "Public Health System",
            description: "Each round prevents three virus cards to increment token",
            action: Constants.ACTION_CONTAIN_VIRUS,
            impactedVirusCards: 3,
        },
        {
            id: "A3",
            type: Constants.CARD_TYPE_ADVANTAGE,
            name: "Advanced Research Labs",
            description: "Each round destroys a virus card token",
            action: Constants.ACTION_DESTROY_VIRUS_TOKEN,
            impactedVirusCards: 1,
        },
        {
            id: "A4",
            type: Constants.CARD_TYPE_ADVANTAGE,
            name: "Safe ports",
            description: "Cant get infected by neighbohrs.",
            action: Constants.ACTION_PREVENT_FROM_NEIGHBOR_INFECTION,
            impactedVirusCards: 1,
        },
        {
            id: "D1",
            type: Constants.CARD_TYPE_DISADVANTAGE,
            name: "Social Ignorance",
            description: "Each round increments a token to a virus card",
            action: Constants.ACTION_INCREMENT_VIRUS_TOKEN,
            impactedVirusCards: 1,
        },
        {
            id: "D2",
            type: Constants.CARD_TYPE_DISADVANTAGE,
            name: "Slums",
            description: "Each round increments two tokens to a virus card",
            action: Constants.ACTION_INCREMENT_VIRUS_TOKEN,
            impactedVirusCards: 2,
        },
        {
            id: "D3",
            type: Constants.CARD_TYPE_DISADVANTAGE,
            name: "Fighiting Narratives",
            description: "Each round increments a token in three virus card",
            action: Constants.ACTION_INCREMENT_VIRUS_TOKEN_CARD,
            impactedVirusCards: 3,
        },
        {
            id: "D4",
            type: Constants.CARD_TYPE_DISADVANTAGE,
            name: "Overloaded hospitals",
            description: "Nullify Advantage Card 2 and Resource Card 4 takes no effect",
            action: Constants.ACTION_PREVENT_FROM_NEIGHBOR_INFECTION,
            impactedResource: ["A2", "R4"],
        },
    ]
}